@startuml
[*] -> wifi模块复位
wifi模块复位->wifi模块初始化
note left of wifi模块初始化
将SOCKA设置为9998,device .myroome.com
将SOCKB设置为9528,255,255,255,255
end note
wifi模块初始化->检查是否连上路由器:初始化成功
wifi模块初始化->wifi模块复位:初始化失败
检查是否连上路由器->是否已向服务器注册:是
检查是否连上路由器->wifi模块复位:否

@enduml