@startuml
scale 1500*1500
start
:获取当前系统时间;
:获取当前的系统状态;
if (当前是助眠状态?) then (是)
        if(用户设定了睡眠时间？) then(是)
                if(助眠结束时间在睡眠开始时间前1小时内?) then(是)
                        :助眠结束后就进入睡眠状态;
                        :助眠结束后执行睡眠灯光、屏幕&音乐停止;
                else(否)
                        :助眠结束后不进入睡眠状态;
                        :到达睡眠时间后，执行呼吸闪烁两次;
                        :如果用户播放音乐，音乐无需停止;
                endif
        else(否)
                :助眠结束后，不进入睡眠状态;
                :不执行呼吸闪烁;
        endif
        stop

else(否)
        :其他流程;
        stop

        @enduml