@startuml
scale 600*600
state 起床前10分钟 {
        起床前10分钟:亮度：执行起床渐亮
        起床前10分钟:音乐：无
        起床前10分钟:音量：无
        起床前10分钟:屏幕：保持睡眠屏幕亮度
}
state 起床前7分钟{
        起床前7分钟:亮度：保持常亮
        起床前7分钟:音乐：播放起床音乐
        起床前7分钟:音量：音量渐强
        起床前7分钟:屏幕：保持睡眠屏幕亮度
}
state 起床前30秒{
        起床前30秒:亮度：保持常亮
        起床前30秒:音乐：播放起床音乐
        起床前30秒:音量：播放起床音乐
        起床前30秒:屏幕：执行屏幕渐亮
}
state 起床时间时{
        起床时间时:亮度：执行日间亮度(自动亮度 or 用户设定的亮度)
        起床时间时:音乐：播放起床铃声
        起床时间时:音量：起床铃声渐强
        起床时间时:屏幕：执行日间屏幕亮度
}

起床前10分钟-->起床前7分钟
起床前7分钟-->起床前30秒
起床前30秒-->起床时间时


@enduml